// Compiles ts/ into src/js/ (one .js per .ts, loaded by the browser as ES modules).
//   npm run build     build once
//   npm run watch     rebuild whenever a .ts file is saved
//   npm run dev       watch + serve on http://localhost:3000
//   npm start         build once + serve
//
// Settings that differ per environment are written to ts/generated/app-config.ts (git-ignored):
//   app.config.json         committed defaults for local development
//   app.config.local.json   optional, git-ignored: your local overrides
//   APP_CONFIG              optional environment variable (JSON) for CI/production: overrides both
//   apikey.txt / GOOGLE_MAPS_API_KEY   the Google Maps key (git-ignored file or environment variable)
import { spawn } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const OUT_DIR = 'src/js';
const GENERATED = 'ts/generated/app-config.ts';
const VENDOR = [['node_modules/@azure/msal-browser/lib/msal-browser.min.js', 'src/vendor/msal-browser.min.js']];

const readJson = file => (existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {});

function writeAppConfig() {
  const config = { ...readJson('app.config.json'), ...readJson('app.config.local.json'), ...(process.env.APP_CONFIG ? JSON.parse(process.env.APP_CONFIG) : {}) };
  const key = (process.env.GOOGLE_MAPS_API_KEY ?? (existsSync('apikey.txt') ? readFileSync('apikey.txt', 'utf8') : '')).trim();
  if (key && !/^[\w-]+$/.test(key)) throw new Error('apikey.txt should contain only the API key (letters, digits, - and _).');
  if (!key) console.warn('No Google Maps key (apikey.txt or GOOGLE_MAPS_API_KEY): the map will show a "no key" message.');
  if (!config.apiBaseUrl || !config.auth?.mode) throw new Error('app.config.json needs "apiBaseUrl" and "auth.mode".');

  mkdirSync('ts/generated', { recursive: true });
  writeFileSync(GENERATED, [
    '// Generated by build.mjs from app.config*.json, APP_CONFIG and apikey.txt. Do not edit or commit.',
    "import type { AppConfig } from '../app-config-types.js';",
    `export const APP_CONFIG: AppConfig = ${JSON.stringify(config, null, 2)};`,
    `export const GOOGLE_MAPS_API_KEY = ${JSON.stringify(key)};`,
    '',
  ].join('\n'));
  console.log(`Config: API ${config.apiBaseUrl}, sign-in "${config.auth.mode}".`);
}

function copyVendor() {
  for (const [from, to] of VENDOR) {
    mkdirSync(to.slice(0, to.lastIndexOf('/')), { recursive: true });
    copyFileSync(from, to);
  }
}

/** Runs tsc; resolves with its exit code. In watch mode it keeps running. */
function tsc(watch) {
  return new Promise(resolve => {
    const args = ['tsc', '-p', '.', ...(watch ? ['--watch', '--preserveWatchOutput'] : [])];
    const child = spawn('npx', args, { stdio: 'inherit', shell: process.platform === 'win32' });
    child.on('exit', code => resolve(code ?? 1));
  });
}

const watch = process.argv.includes('--watch');
const serve = process.argv.includes('--serve');

// Claim the port before touching any files, so a second `npm run dev` stops cleanly
// instead of wiping the output another one is serving.
if (serve) {
  try { await (await import('./server.js')).start(); }
  catch (err) { console.error(err.message ?? err); process.exit(1); }
}

writeAppConfig();
copyVendor();
rmSync(OUT_DIR, { recursive: true, force: true }); // no stale modules from renamed/deleted .ts files

if (watch) {
  await tsc(true);
} else {
  const code = await tsc(false);
  if (code !== 0) {
    console.error('Build failed.');
    process.exitCode = code;
  } else {
    console.log(`Built ${OUT_DIR}/.`);
  }
}
